project:
  type: website

website:
  title: "johnowhitaker.dev"
  site-url: "https://johnowhitaker.dev"
  navbar:
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: all.qmd
        text: Everything Feed
      - text: "More"
        menu:
          - href: tsbabn.qmd
            text: TSBABN
          - resume.md
          - books.qmd
          - blogs.md
          - yt.md
          - appearances.qmd
          - things.md
          - icon: rss
            text: RSS Feed
            href: "https://johnowhitaker.dev/index.xml"
          - now.md
      
  
  twitter-card:
     creator: "@johnowhitaker"
     card-style: summary

format:
  html:
    theme: darkly
    css: styles.css
    toc: true



